### ISSUE TITLE
Setup Test Environment for Frontend and Backend

### ISSUE THREAD

**Issue by maxtse25** [nitishragu12/Capstone-Project#51]
We need to establish a testing environment for our application to ensure that both the frontend (React) and backend (Flask) are properly tested. This will involve configuring the necessary tools and scripts to run unit and integration tests efficiently.

### Frontend (React):
1. Testing Frameworks:
- [ ] Install and configure Jest for unit testing.
- [ ] Install and configure React Testing Library for component testing.

2. Configuration Files:
- [ ] Create or update jest.config.js for Jest configuration.
- [ ] Set up setupTests.js if needed for React Testing Library.

3. Environment Variables
- [ ] Create a .env.test file for test-specific environment variables.

4. Test Scripts:
- [ ] Add or update test scripts in package.json:
`"scripts": {
  "test": "jest",
  "test:watch": "jest --watch",
  "test:coverage": "jest --coverage"
}`

5. Docker Configuration:
- [ ] Dockerfile: Ensure the Dockerfile for the frontend includes necessary dependencies for testing.

### Backend (Flask):

1. Testing Frameworks:
- [ ] Install and configure pytest for unit and integration testing.
- [ ] Install and configure Flask-Testing if needed for Flask-specific testing utilities.

2. Configuration Files:
- [ ] Create or update pytest.ini for pytest configuration.
- [ ] Ensure test configuration is included in the Flask application setup.

3. Test Scripts:
- [ ] Add or update test scripts in setup.py or relevant files:
`pytest --maxfail=1 --disable-warnings -q`

4. Docker Configuration:
- [ ] Dockerfile: Ensure the Dockerfile for the frontend includes necessary dependencies for testing.

### Tasks:
-  Install and configure Jest and React Testing Library for the frontend.
-  Set up the necessary configuration files for frontend testing.
-  Update Dockerfile and docker-compose.yml for frontend testing.
-  Add test scripts to package.json.
-  Install and configure pytest and Flask-Testing for the backend.
-  Update Flask configuration for testing.
-  Update Dockerfile and docker-compose.yml for backend testing.
-  Add test scripts for the backend.
-  Implement mocking where necessary for both frontend and backend tests.

### Additional Notes:

- Ensure that test scripts are compatible with the CI/CD pipeline.
- Document any setup steps or configuration changes for future reference.
